//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace studentCRUD26042024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        public int id { get; set; }
        [Display(Name ="Student Name")]
        public string name { get; set; }
        [Display(Name ="Division")]
        public string div { get; set; }
        [Display(Name ="Mobile Number")]
        public Nullable<decimal> contact { get; set; }
        public string gender { get; set; }
    }
}
